name: Hola Mundo Workflow
on:
  push:
    branches:
      - main
jobs:
  hola-mundo: 
   # The type of runner that the job will run on
   runs-on: ubuntu-latest
   steps:
    - name: Print greeting
run: echo "Hola Mundo!"
